// <auto-generated />
using System;
using Aseguradora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aseguradora.Migrations
{
    [DbContext(typeof(AseguradoraContext))]
    [Migration("20220702135835_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Aseguradora.Models.Cliente", b =>
                {
                    b.Property<string>("CedulaCliente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Edad")
                        .HasColumnType("smallint");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CedulaCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Aseguradora.Models.ClienteSeguro", b =>
                {
                    b.Property<string>("CodigoSeguro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CedulaCliente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.HasKey("CodigoSeguro", "CedulaCliente");

                    b.HasIndex("CedulaCliente");

                    b.ToTable("ClienteSeguro");
                });

            modelBuilder.Entity("Aseguradora.Models.Seguro", b =>
                {
                    b.Property<string>("CodigoSeguro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrimaSeguro")
                        .HasColumnType("real");

                    b.Property<float>("SumaAsegurada")
                        .HasColumnType("real");

                    b.HasKey("CodigoSeguro");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("Aseguradora.Models.ClienteSeguro", b =>
                {
                    b.HasOne("Aseguradora.Models.Cliente", "Cliente")
                        .WithMany("ClientesSeguros")
                        .HasForeignKey("CedulaCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aseguradora.Models.Seguro", "Seguro")
                        .WithMany("ClientesSeguros")
                        .HasForeignKey("CodigoSeguro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("Aseguradora.Models.Cliente", b =>
                {
                    b.Navigation("ClientesSeguros");
                });

            modelBuilder.Entity("Aseguradora.Models.Seguro", b =>
                {
                    b.Navigation("ClientesSeguros");
                });
#pragma warning restore 612, 618
        }
    }
}
